# These are supported funding model platforms

github: [codebard]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: [codebard]# Replace with a single Patreon username
custom: ["https://www.paypal.me/codebard", codebard.com]
